apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: poc5
  name: sharedvol
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /config
