apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: poc5
  name: sharedpvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
