apiVersion: v1
kind: Pod
metadata:
  namespace: poc5
  name: writer-pod
spec:
  containers:
  - name: write-container
    image: zetolnx/pk-poc5-writer:v0.0.2
    volumeMounts:
    - name: storage
      mountPath: /config
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: sharedpvc
