apiVersion: v1
kind: Pod
metadata:
  namespace: poc5
  name: reader-pod
spec:
  containers:
  - name: reader-container
    image: zetolnx/pk-poc5-reader:v0.0.1
    volumeMounts:
    - name: storage
      mountPath: /config
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: sharedpvc
